// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xamneaematcdtpehjxlt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhhbW5lYWVtYXRjZHRwZWhqeGx0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MTUzODAsImV4cCI6MjA2MDE5MTM4MH0.V1W0jhz3Mbx0LV9Aud9sMHEJazvG1TcJMZ6XzU7sPyw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);